/*
 * Copyright (C) 2015-2026 IoT.bzh Company
 * Author: Fulup Ar Foll <fulup@iot.bzh>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

extern crate dbcparser;
use dbcparser::prelude::*;
use env_logger::Env;

use std::env;
use std::io::{self, Error};

const HEADER: &str = "
// -----------------------------------------------------------------------
//              <- DBC file Rust mapping ->
// -----------------------------------------------------------------------
//  Do not edit this file it will be regenerated automatically by cargo.
//  Check:
//   - build.rs at project root for dynamically mapping
//   - example/demo/dbc-log/??? for static values
//  Reference: iot.bzh/Redpesk canbus-rs code generator
// -----------------------------------------------------------------------

// Tell rustfmt (stable) to skip formatting this whole file
#[rustfmt::skip]

#![allow(
warnings,
clippy::all,
clippy::pedantic,
clippy::nursery,
clippy::redundant_field_names,
clippy::similar_names
)]
";

fn main() -> io::Result<()> {
    // Initialize logging backend for the `log` facade (idempotent).
    let env = Env::default().default_filter_or("info");
    let _ = env_logger::Builder::from_env(env).format_timestamp_millis().try_init();

    let args: Vec<String> = env::args().collect();

    if args.len() != 3 {
        log::info!("SYNTAX-Error => can-dbc '/xxx/file.dbc' '/yyyy/candump.log'");
        log::info!(
            "example: {} 'examples/dbc-log/canforge_dbc_complete_norm.dbc' 'examples/dbc-log/candump.log'",
            args[0]
        );
        return Err(Error::other("invalid input arguments"));
    }

    let dbcfile = args[1].as_str();
    let dumpfile = args[2].as_str();

    DbcParser::new("Demo")
        .dbcfile(dbcfile)
        .outfile(dumpfile)
        .header(HEADER)
        .generate()?;

    Ok(())
}
